name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    collapse-after: 3
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    collapse-after: 3
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: '🧰 Maintenance'
    collapse-after: 3
    label: 'chore'
  - title: 'Documentation'
    collapse-after: 3
    label: 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - 'skip-changelog'
exclude-contributors:
  - 'thpham'
replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
  - search: 'thpham'
    replace: 'Thomas Pham'
autolabeler:
  - label: 'docs'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
template: |
  ## Changes

  $CHANGES