[tool.poetry]
name = "aspic"
version = "0.1.0"
description = ""
authors = ["Thomas Pham <thomas.pham@ithings.ch>"]

[tool.poetry.dependencies]
python = "^3.9"
kopf = {extras = ["full-auth"], version = "^1.35.3"}
PyYAML = "^6.0"
pykube = "^0.15.0"
Jinja2 = "^3.0.3"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
