# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.7.x check https://cert-manager.io/docs/installation/upgrading for 
# breaking changes
{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: aspic-operator-ca-root
  labels:
    {{- include "aspic-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: operator-webhook
  labels:
    {{- include "aspic-operator.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: ClusterIssuer
    name: aspic-operator-ca-root
  secretName: operator-webhook-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - {{ include "aspic-operator.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "aspic-operator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    - update-streams.webook.aspic.io
    - mutate-pods.webhook.aspic.io
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - client auth
    - server auth
{{- end }}