
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aspic-operator.fullname" . }}
  labels:
    {{- include "aspic-operator.labels" . | nindent 4 }}
rules:
  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]

  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: ["*"]
    resources: ["pods", "jobs", "deployments", "deployments/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  - apiGroups: [config.aspic.io]
    resources: [update-streams]
    verbs: [get, list, watch, patch]
