apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.core.aspic.io
  labels:
    app: aspic
    aspic.io/crd-install: "true"
    component: projects.core.aspic.io-crd
spec:
  scope: Namespaced
  group: core.aspic.io
  names:
    kind: Project
    listKind: ProjectList
    singular: project
    plural: projects
    shortNames:
      - p
    categories:
      - aspic
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Channel
          description: The update channel name
          jsonPath: .spec.project.channel
          type: string
        - name: Ready
          description: The state of the custom resource
          jsonPath: .status.conditions[?(@.type=="Ready")].status
          type: string
        - name: Warnings
          description: Warnings related to the custom resource
          jsonPath: .status.conditions[?(@.type=="Warning")].status
          type: string
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                channel:
                  description: The update channel name
                  type: string
                  enum:
                    - stable
                    - candidate
                    - develop
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
