apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aspic-operator.fullname" . }}
  labels:
    {{- include "aspic-operator.labels" . | nindent 4 }}
spec:
  # reason: https://kopf.readthedocs.io/en/stable/deployment/#cluster-deployment
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "aspic-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aspic-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aspic-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{- if .Values.command }}
          {{- range .Values.command }}
            - {{ . }}
          {{- end }}
          {{- else }}
            - kopf
            - run
          {{- end }}
          args:
          {{- if .Values.args }}
          {{- range .Values.args }}
            - {{ . }}
          {{- end }}
          {{- end }}
            - --all-namespaces
            - main.py
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
