apiVersion: v1
kind: Service
metadata:
  name: {{ include "aspic-operator.fullname" . }}
  labels:
    {{- include "aspic-operator.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.openshift.enabled }}
    service.beta.openshift.io/serving-cert-secret-name: operator-webhook-cert
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.api.enabled }}
    - name: api
      port: {{ .Values.api.service.port }}
      targetPort: api
      protocol: TCP
    {{- end }}
    - name: webhook
      port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "aspic-operator.selectorLabels" . | nindent 4 }}
