apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
  labels:
    stage: dev
spec:
  disableAdmin: false
  notifications:
    enabled: true
  grafana:
    enabled: false
  prometheus:
    enabled: false
  applicationSet: {}
  server:
    grpc:
      ingress:
        enabled: true
    ingress:
      enabled: true
    insecure: true
    autoscale:
      enabled: true
  controller:
    processors:
      operation: 10
      status: 20
    resources: {}
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'

